---
- hosts: All
  roles:
  - general

- hosts: 127.0.0.1
  roles:
  - observer
  vars: 
    tape_config_file: configlatest1.yaml

- hosts: 127.0.0.1
  roles:
  - traffic
  vars: 
    tape_config_file: configlatest2.yaml

- hosts: localhost
  roles:
  - traffic
  vars: 
    tape_config_file: configlatest3.yaml