---
- name: pre check
  debug: 
    msg: will use file {{tape_config_file}} to start tape on node {{ ansible_facts['nodename'] }}

- name: observer task
  shell: source /etc/profile && docker run -d -e TAPE_LOGLEVEL=debug --network host -v /tmp/tape/files:/config ghcr.io/hyperledger-twgc/tape:edge tape observer -c /config/{{tape_config_file}}
