---
- name: mkdir
  shell: mkdir -p /tmp/tape && chmod -R 755 /tmp/tape 

- name: copy file to /tmp/tape
  copy:
    src: /Users/yuanyi/OpenSource/distributedtape/files
    dest: /tmp/tape
    directory_mode: yes
    force: yes
  
- name: observer task
  shell: source /etc/profile && docker run -d --rm -e TAPE_LOGLEVEL=debug --network host -v $PWD:/config ghcr.io/hyperledger-twgc/tape:edge tape verion
  #observer -c /config/test/configlatest.yaml -n 500

#- name: clean up
#  shell: source /etc/profile && docker rm tape
